### PR TITLE
Labels and Tag Cloud

### PR DESCRIPTION
**Pull request by mattheu**
https://github.com/humanmade/hm-pattern-library/issues/79

I've built the labels as originally mocked up, but i'm concerned they're a little... overly fancy. I've made the punch hole ornament optional for now, but maybe best to drop completely. Thoughts?

image

image

### CODE REVIEW

**Comment by missjwo** [comment]
i think there should be only one version of the labels. What i do liek is the fact taht the lebals  wit eth punch hole are different to the tags visually - but you are right it seems a bit fancier.

the fact you have made it an eitehr or option of which type oflabel styling you get i think is a godo way to be able to choice  either one. Im trying to work out where we use catergories/ labels currently. 

do you have a screenshot  of it in place?

**Comment by mattheu** [comment]
No I don't have another screenshot - this is just done in the pattern library.

I'm doing this with the project catalog in mind, but thinking about introducing something like this to the handbook to allow us to flag status such as `in-progress`. We don't really have a common way of doing this currently, and I'm trying to come up with some design that is pretty generic.

The punchole style looks good, but only really works for traditional concept of 'tags', and i'm not sure it works so well as a more generic style

**Comment by mattheu** [comment]
OK I've removed the fancier version - stuck with the basic one. This is good to go.

**Comment by mattheu** [comment]
OK this is pretty insignificant without the punchholes - and useful so I"m going to merge this one.

**Pull request merged**
