### PR TITLE
Separate type + type mixins. Add link mixin

### PR DESCRIPTION
**Pull request by mattheu**
Makes it easier to reuse.

See https://github.com/humanmade/hm-pattern-library/issues/89

### CODE REVIEW

**Comment by mattheu** [comment]
@rmccue Does this work for you?

**Comment by rmccue** [comment]
lgtm, but I think the buttons mixin is still using the `a:link` selector?

**Comment by mattheu** [comment]
The buttons have some styles for `&:link`, which are required if you apply this class to a link element. But it isn't necessary to do that.

There was a use of `@extend a:link`, which I don't think is actually necessary - I removed this.

Theres also a dependency on the loading indicator, but I made this optional just in case you're not including this.

**Comment by rmccue** [comment]
Needs a rebuild for the gh-pages branch.

**Comment by mattheu** [comment]
Rebuilt

**Pull request merged**
